# Generated by Django 3.2.5 on 2021-07-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210710_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='age',
        ),
        migrations.AddField(
            model_name='contact',
            name='close',
            field=models.BooleanField(blank=True, choices=[(1, 'yes'), (0, 'no')], default=1),
        ),
        migrations.AddField(
            model_name='contact',
            name='comments',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='contact',
            name='duration',
            field=models.CharField(blank=True, choices=[('Short', 'Short'), ('Medium', 'Medium'), ('Long', 'Long')], default='Medium', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='interaction',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=7, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='lay',
            field=models.BooleanField(blank=True, choices=[(1, 'yes'), (0, 'no')], default=0),
        ),
        migrations.AddField(
            model_name='contact',
            name='looks',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=7, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='nationality',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='person_age',
            field=models.IntegerField(blank=True, choices=[(16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45)], default=22, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='reply',
            field=models.BooleanField(blank=True, choices=[(1, 'yes'), (0, 'no')], default=0),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
