# Generated by Django 3.2.5 on 2021-07-11 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_contact_person_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='person_age',
            new_name='age',
        ),
        migrations.AddField(
            model_name='contact',
            name='date_apporach',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
