# Generated by Django 3.2.5 on 2021-07-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210711_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.BooleanField(blank=True, choices=[(1, 'yes'), (0, 'no')], default=0),
        ),
    ]
