# Generated by Django 3.2.5 on 2021-07-11 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contact_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='date_apporach',
            new_name='date_approach',
        ),
    ]
