# Generated by Django 3.2.5 on 2021-08-01 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_contact_date_approach'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='time_approach',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
