# Generated by Django 3.2.5 on 2021-08-01 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contact_gym'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='gym',
            new_name='user',
        ),
    ]
