# Generated by Django 3.2.5 on 2021-08-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_user_contact_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='close',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lay',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='reply',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=30),
        ),
    ]
