# Generated by Django 3.2.5 on 2021-08-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210804_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='group_size',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=1, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.CharField(default='Unkown', max_length=30),
            preserve_default=False,
        ),
    ]
